version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: topup-wallet-app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "${PORT}:8080" 
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=disable
      - PORT=8080
      - SERVER_HOST=${SERVER_HOST}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=0
    networks:
      - app-network

  postgres:
    image: postgres:16.2
    container_name: topup-wallet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  redis:
    image: redis:7.2
    container_name: topup-wallet-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}  
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis-data: